import { v4 as uuidv4 } from "uuid";
const Data = {
  courses: [
    {
      id: uuidv4(),
      title: "دوره تخصصی جمشید کَل",
      description:
        "با برگزاری دوباره دوره انگولار خود را در مسیری که انتخاب کردید به سمت موفقیت در فریمورک آنگولار سوق دهید. این دوره ...",
      teacher: "مازیار قلی پور",
      lesson: 180,
      rate: "4/5",
      date: 42.5,
      price: 999.999,
      numberOfStudents: 50,
      archive: "پُگ شده",
      image: require("../../../Assets/alexander-shatov.jpg"),
      level: "همه سطح",
      view: 110,
    },
    {
      id: uuidv4(),
      title: "دوره تخصصی تقی کُمیسر",
      description:
        "با برگزاری دوباره دوره انگولار خود را در مسیری که انتخاب کردید به سمت موفقیت در فریمورک آنگولار سوق دهید. این دوره ...",
      teacher: "مازیار قلی پور",
      lesson: 180,
      rate: "4/5",
      date: 42.5,
      price: 999.999,
      numberOfStudents: 50,
      archive: "تکمیل شده",
      image: require("../../../Assets/alexander-shatov.jpg"),
      level: "ساده",
      view: 110,
    },
    {
      id: uuidv4(),
      title: "دوره تخصصی شال خی",
      description:
        "با برگزاری دوباره دوره انگولار خود را در مسیری که انتخاب کردید به سمت موفقیت در فریمورک آنگولار سوق دهید. این دوره ...",
      teacher: "مازیار قلی پور",
      lesson: 180,
      rate: "4/5",
      price: 999.999,
      date: 42.5,
      numberOfStudents: 50,
      archive: "آرشیو شده",
      image: require("../../../Assets/alexander-shatov.jpg"),
      level: "پیشرفته",
      view: 110,
    },
    {
      id: uuidv4(),
      title: "دوره تخصصی علی بخت",
      description:
        "با برگزاری دوباره دوره انگولار خود را در مسیری که انتخاب کردید به سمت موفقیت در فریمورک آنگولار سوق دهید. این دوره ...",
      teacher: "مازیار قلی پور",
      lesson: 180,
      rate: "4/5",
      date: 42.5,
      price: 999.999,
      numberOfStudents: 50,
      archive: "ضپط شده",
      image: require("../../../Assets/alexander-shatov.jpg"),
      level: "نرمال",
      view: 110,
    },
    {
      id: uuidv4(),
      title: "دوره عمومی حاج حسن کریمی کمیلی",
      description:
        "با برگزاری دوباره دوره انگولار خود را در مسیری که انتخاب کردید به سمت موفقیت در فریمورک آنگولار سوق دهید. این دوره ...",
      teacher: "مازیار قلی پور",
      lesson: 180,
      rate: "4/5",
      date: 42.5,
      price: 999.999,
      numberOfStudents: 50,
      archive: "وجی شده",
      image: require("../../../Assets/vipul.jpg"),
      level: "نرمال",
      view: 110,
    },
    {
      id: uuidv4(),
      title: "دوره تخصصی سید کبیر",
      description:
        "با برگزاری دوباره دوره انگولار خود را در مسیری که انتخاب کردید به سمت موفقیت در فریمورک آنگولار سوق دهید. این دوره ...",
      teacher: "مازیار قلی پور",
      lesson: 180,
      rate: "4/5",
      date: 42.5,
      price: 999.999,
      numberOfStudents: 50,
      archive: "کُمیسر شده",
      image: require("../../../Assets/alexander-shatov.jpg"),
      level: "نرمال",
      view: 110,
    },
    {
      id: uuidv4(),
      title: "دوره عمومی حاج کریم کریمی کمیلی",
      description:
        "با برگزاری دوباره دوره انگولار خود را در مسیری که انتخاب کردید به سمت موفقیت در فریمورک آنگولار سوق دهید. این دوره ...",
      teacher: "مازیار قلی پور",
      lesson: 180,
      rate: "4/5",
      date: 42.5,
      price: 999.999,
      numberOfStudents: 50,
      archive: "بخت چه",
      image: require("../../../Assets/alexander-shatov.jpg"),
      level: "نرمال",
      view: 110,
    },
  ],
};

export default Data;
